version: '3'
services:
    app:
        restart: always
        build: .
        container_name: 'app'
        working_dir: '/home/dogscox'
        tty: true
        ports:
            - 8080:5000
        volumes:
            - .:/home/dogscox
